### ISSUE TITLE
Raspberry Pi ARM Binaries

### ISSUE THREAD

**Issue by MrChrisJ** [ipfs/ipfs-desktop#165]
Hey is it possible to get this working for the Arm processors. I would like to add this to the Fullnode project. I did try installing but as expected was met with errors.

**Comment by whyrusleeping** [comment]
@MrChrisJ could you provide an error log from the build? I have several raspberry pi's I can spin up to help debug this for you. (we can even probably add a special raspberry pi build to dist.ipfs.io)

**Comment by dignifiedquire** [comment]
@MrChrisJ I just pushed a version to master that should work with npm@2 please give it a try

**Comment by MrChrisJ** [comment]
Hey @dignifiedquire thanks very much. I did get v3 working, still getting these errors on the Pi:
https://gist.github.com/MrChrisJ/14e9cc728cf608dcd97a

I have Station working on OS X just fine. I installed it minutes ago after your commit.

**Comment by dignifiedquire** [comment]
@MrChrisJ the error means it's not able to connect to the npm registry. probably some network issue on the config side of your box

**Comment by MrChrisJ** [comment]
@dignifiedquire ooops ```sudo killall tor```, let's see how this goes :). I did originally get a different error though on the next stage but it's downloading now. Thanks for your time.

**Comment by MrChrisJ** [comment]
After a bit of fiddling I did get working. The application will run for about 10-20 mins before crashing:
https://gist.github.com/MrChrisJ/61ff07629cb4c79bcfd5#file-20160219-ipfs_station_crashing_rpi2-txt

I will try to install it again to see if there was a problem with any of the packages.

**Comment by MrChrisJ** [comment]
I have tried the new download and I am back to the same error as before. This looks like something to do with NPM and the Pi so I have asked some colleagues who are familiar with NodeJS:  
https://gist.github.com/MrChrisJ/14e9cc728cf608dcd97a
https://gist.github.com/MrChrisJ/61ff07629cb4c79bcfd5#file-error-trying-to-install-ipfs-station

That is with all the Proxy settings checked in the system as well as NPM Config. I tried fresh installs of both Wheezy and Jessie. Double checked everything. Will see what my friends come back with.

**Comment by ralphtheninja** [comment]
@MrChrisJ This sounds like it's related to npm and not station. Have you tried installing anything else with npm?

**Comment by ralphtheninja** [comment]
Well the `ECONNRESET` sounds related to npm and your connection, not the crash.

**Comment by hacdias** [comment]
This is quite an old issue. I'm closing this for now. However, if anyone needs or would like to have arm 7 binaries, please feel free to ping me here and we can see what can be done about the situation.

**Comment by insign** [comment]
ARM looks like a trend. Trying to run in my Pi4. Maybe from souce. Just saying that this is important.

**Comment by lidel** [comment]
Reopening as, it should be possible to re-evaluate what is needed to run IPFS Desktop on inexpensive ARM64 hardware like RaspberryPi 4.

Kubo already provides ARM64 build that I confirmed works fine on my RPi4.

**Comment by SgtPooki** [comment]
There are a few requests related to ARM support:

* https://github.com/ipfs/ipfs-desktop/issues/2656
* https://github.com/ipfs/ipfs-desktop/issues/1827
* https://github.com/ipfs/ipfs-desktop/pull/1856#issuecomment-1626371157

I am open to supporting ARM64 on all platforms (especially mine!) 

I think calling electron-builder manually would be easier than installing dependencies dynamically during runtime, but I can investigate more.

Two good resources I found are: 
* https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi
* https://github.com/orgs/community/discussions/25319

So it seems like the actions needed are:

1. Figure out what arm64 hosted-runner kubo-releaser is using, and use that for some electron-builder tasks
2. call electron-builder from arm64/armv71 hosted-runners with flags as mentioned in https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi and at https://www.electron.build/cli

**Comment by SgtPooki** [comment]
I [searched for electron-builder stuff in github CI files](https://github.com/search?q=path%3A.github%2Fworkflows%2F*.yml%20electron-builder&type=code) and found a few examples for us to look at.

https://github.com/jgraph/drawio-desktop seems like a promising place to look for configs and stuff to update our electron-builder flow.. seems like a pretty popular app that's up to date with [a really clear electron-builder integration](https://github.com/search?q=repo%3Ajgraph%2Fdrawio-desktop%20electron-builder&type=code), and multiple arch builds: including mac universal build...
