### ISSUE TITLE
Install from AUR

### ISSUE THREAD

**Issue by act28** [ipfs/ipfs-desktop#1890]
- OS: [e.g. macOS, Windows, Linux]
 - Version of IPFS Desktop [e.g. 0.11.1]

Linux Manjaro
ipfs-desktop version 0.16.2

**Describe the bug**

`> electron-builder install-app-deps` throws `Error: Cannot find module 'fs/promises'

**To Reproduce**

1. Install from AUR
2. Fails on `electron-builder install-app-deps` step

**Expected behavior**

Installs successfully

**Screenshots**

**Additional context**

[ipfs-desktop-aur-install.log](https://github.com/ipfs/ipfs-desktop/files/6958781/ipfs-desktop-aur-install.log)

**Comment by lidel** [comment]
@act28 i am confused what you mean by "Install from AUR". What exact steps / commands are you executing? what are you trying to accomplish?

**Comment by act28** [comment]
@lidel installed from Archlinux User Repository (AUR) package. The AUR package builds from tar.gz source.

**Comment by Paradox-AT** [comment]
I am facing the same issue. I am installing using yay from AUR

**Comment by act28** [comment]
Really, `github-actions` bot? I don't know how much more explicit I need to be. How much "more" information do you need? 
It even says on the `README.md` under the `Install` heading for `Linux/FreeBSD`:

```
AUR (maintained by @RubenKelevra) Use the ipfs-desktop package
```

**Comment by Paradox-AT** [comment]
Really, `github-actions` again??

**Comment by Paradox-AT** [comment]
What else is needed??

**Comment by kn0wmad** [comment]
I also have this issue installing from AUR using yay.  Please advise

**Comment by Paradox-AT** [comment]
It has started working, I think we can close it now

**Comment by lidel** [comment]
_Apologies for the bot – been afk on short vacation_

I've merged a bunch of dependency updates yesterday, one of them most likely fixed this.
Thanks for reporting and confirming it got fixed!

**Comment by kn0wmad** [comment]
Hi there, my same issue remains.  Tried a clean build today, no luck (AUR/yay)

**Comment by simonloewe** [comment]
Same issue here

**Comment by lidel** [comment]
My guess is that you need to fix build script at AUR –  it should leverage `package-lock.json` by using `npm ci` :

```diff
build() {
    cd "$pkgname-$pkgver"
-    npm install --cache "$srcdir/npm-cache"
+    npm ci --no-audit --progress=false --cache "$srcdir/npm-cache"
    npm run-script build
    npx electron-builder build --linux pacman
}
```

Anyone familiar with AUR able to submit the fix?

**Comment by lidel** [comment]
cc @RubenKelevra perhaps?

**Comment by RubenKelevra** [comment]
> cc @RubenKelevra perhaps?

Yeah I'm the maintainer for the package, so I'm happy to help.

Let me have a look at yours fix :)

**Comment by RubenKelevra** [comment]
@lidel I've moved the dependency fetching to prepare() where it belongs (this might have been the issue - not sure) - I don't use yay.

It still builds fine with makepkg.

@act28 @simonloewe @kn0wmad @Paradox-AT can you recheck if it installs on your systems and if not, please try building it manually with `makepkg` instead of yay, and report back if that changes anything.

**Comment by RubenKelevra** [comment]
@lidel that's off-topic but as we're already at the build script: Do we really need all those dependencies for operation? 

The array of `depends=*` shows what's expected to be installed as long as the program is installed, as it's needed for running the program. And I don't know if we really need all of that stuff.

`makedepends=*` look fine to me.

**Comment by act28** [comment]
@RubenKelevra `0.18.1-1` installs correctly now (with `pamac`). Didn't require manual installation.

**Comment by lidel** [comment]
Cool, so is the installation issue solved? Can you confirm @simonloewe? 

> Do we really need all those dependencies for operation?
> ```
> depends=(c-ares ffmpeg gtk3 http-parser libevent libvpx libxslt libxss minizip nss re2 snappy libnotify libappindicator-gtk3)`
> ```

@RubenKelevra :man_shrugging: – in theory ipfs-desktop dependencies are the same as any other Electron app, only caveat being libappindicator for tray icon. If you know other Electron apps in AUR, that may be good baseline.

Also,  here are deps from `.deb` package:
```console
$ dpkg -I ipfs-desktop-0.18.1-linux-amd64.deb
...
 Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
 Recommends: libappindicator3-1
```

**Comment by RubenKelevra** [comment]
> 
> > Do we really need all those dependencies for operation?
> > ```
> > depends=(c-ares ffmpeg gtk3 http-parser libevent libvpx libxslt libxss minizip nss re2 snappy libnotify libappindicator-gtk3)`
> > ```
> 
> @RubenKelevra :man_shrugging: – in theory ipfs-desktop dependencies are the same as any other Electron app, only caveat being libappindicator for tray icon. If you know other Electron apps in AUR, that may be good baseline.
> 
> Also,  here are deps from `.deb` package:
> ```console
> $ dpkg -I ipfs-desktop-0.18.1-linux-amd64.deb
> ...
>  Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
>  Recommends: libappindicator3-1
> ```

I mean some of them might be necessary, but I can't think of a good reason we need ffmpeg for example 🤔

**Comment by kn0wmad** [comment]
> @lidel [I've moved the dependency fetching to prepare() where it belongs (this might have been the issue - not sure) - I don't use yay. I also changed to your npm command.](https://aur.archlinux.org/cgit/aur.git/commit/?h=ipfs-desktop&id=c78e9755e927f28ee4ab49014f0655942a97915f)
> 
> It still builds fine with makepkg.
> 
> @act28 @simonloewe @kn0wmad @Paradox-AT can you recheck if it installs on your systems and if not, please try building it manually with `makepkg` instead of yay, and report back if that changes anything.

I had a series of unrelated problems, but did get it to build on yay.  Thank you very much for your time fixing this

**Comment by RubenKelevra** [comment]
@lidel I think this can be closed :)

**Comment by simonloewe** [comment]
Sorry for the late answer. I solved this by updating from node 11 to node 14. Can be closed in regards to my issue.

**Comment by RubenKelevra** [comment]
> Sorry for the late answer. I solved this by updating from node 11 to node 14. Can be closed in regards to my issue. 

So how did you end up with node 11? 🤔

**Comment by simonloewe** [comment]
I have a docker image to run it all and there, out of a copy past mistake of mine, I ended up installing node11 in.

**Comment by lidel** [comment]
Thanks!

**Comment by RubenKelevra** [comment]
> I have a docker image to run it all and there, out of a copy past mistake of mine, I ended up installing node11 in.

Ah! So I'll add a version check to that :)
