### ISSUE TITLE
Could not connect to the IPFS API

### ISSUE THREAD

**Issue by Heynsss** [ipfs/ipfs-desktop#2191]
- OS:  Windows
- Version of IPFS Desktop [e.g. 0.21.0]

I keep getting the following error:

![Error IPFS](https://user-images.githubusercontent.com/102860953/176657303-b06128c0-da66-487f-b566-e4eea5e1e060.jpg)

Can you please help me?

ATTACH LOGS

2022-06-30T08:32:53.668Z error: [ipfsd] start daemon undefined
2022-06-30T08:58:55.298Z error: Key 'FN_LAUNCH_WEB_UI_FOO' is not a valid analyticsKey
2022-06-30T08:58:55.919Z error: Key 'FN_LAUNCH_WEB_UI_FOO' is not a valid analyticsKey
2022-06-30T09:06:44.257Z error: [ipfsd] start daemon undefined
2022-06-30T09:06:52.110Z error: [ipfsd] start daemon undefined
2022-06-30T09:08:16.225Z error: Key 'FN_LAUNCH_WEB_UI_FOO' is not a valid analyticsKey
2022-06-30T09:13:58.913Z error: [ipfsd] start daemon undefined
2022-06-30T09:17:44.433Z error: Key 'FN_LAUNCH_WEB_UI_FOO' is not a valid analyticsKey
2022-06-30T09:55:18.488Z error: [ipfsd] start daemon undefined
2022-06-30T10:31:48.411Z error: [ipfsd] start daemon undefined
2022-06-30T10:33:28.548Z error: [ipfsd] start daemon undefined
2022-06-30T10:34:31.155Z error: [ipfsd] start daemon undefined

Thanks

**Comment by lidel** [comment]
I think this is a bug:

https://github.com/ipfs/ipfs-desktop/blob/e16b1e7374b0d614c4bd2416b7b75cd58f45d85e/src/webui/index.js#L143

@hacdias should be an easy fix, mind taking a look?

**Comment by hacdias** [comment]
I think there are two different "problems" happening here:

1. `Key 'FN_LAUNCH_WEB_UI_FOO' is not a valid analyticsKey`, which is, indeed, what you mentioned. Addressed in #2224.
2. `start daemon undefined`, which seems that starting the daemon is indeed failing, but there is some problem with the error. Still taking a look at this.

**Comment by SgtPooki** [comment]
Both of the PRs have been merged, so this should be resolved. Please let us know if you're still experiencing an issue by re-opening this issue

**Comment by rahulreddy27** [comment]
this error still persists. I updated to the latest version of the desktop app, temporarily for a few hours it worked and now it's showing the error.
